server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: calculator-api
  messages:
    basename: messages
  jackson:
    default-property-inclusion: non_null
springdoc:
  packagesToScan: com.bloomberg.calculatorapi.web.controllers

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_HOST:http://localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true

security:
  basic:
    enable: false

management:
  security:
    enabled: false

logging:
  level:
    org:
      springframework: INFO
